name: user-info

services:
  client_db:
    restart: always
    image: postgres:16.9-alpine3.21
    container_name: client_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres/scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"

