# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - jacoboestreicher-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment and install dependencies
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Django management commands
        run: |
          cd backend 
          source venv/bin/activate
          python3 manage.py collectstatic --noinput --settings=myproject.settings
          # python3 manage.py migrate --settings=myproject.settings  # Uncomment if needed
        
      # Optional: Add step to run tests here
      - name: Run tests
        run: |
          cd backend
          source venv/bin/activate
          # python3 manage.py test  # Uncomment to run tests

      - name: Create deployment package
        run: |
          cd backend
          # Create a clean deployment package
          zip -r ../deployment.zip . -x "venv/*" "*.pyc" "__pycache__/*" ".git/*" "*.log"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip deployment.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31761D2B52924F54A5B3AFDAE345C5EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DFE8AA45A9D4152820FB1FDB8DD3850 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6C210F7ADA041E8B5A42FE1E3B8ABFF }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'jacoboestreicher-backend'
          slot-name: 'Production'