name: Build and deploy Python app to Azure Web App - jacoboestreicher-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd backend
          python3 manage.py collectstatic --noinput

      - name: Zip project (for Azure deploy)
        run: |
          cd backend
          zip -r ../release.zip . -x "venv/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31761D2B52924F54A5B3AFDAE345C5EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DFE8AA45A9D4152820FB1FDB8DD3850 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6C210F7ADA041E8B5A42FE1E3B8ABFF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jacoboestreicher-backend'
          package: .
